version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - ENVIRONMENT=development
      - PORT=3001
      - HOST=0.0.0.0
      - DATABASE_PATH=/app/data/todos.db
    volumes:
      - todo_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - todo-network

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  todo_data:
    driver: local

networks:
  todo-network:
    driver: bridge